version: "3.4"
services:
  haproxy:
    container_name: "haproxy"
    #image: teamwork/haproxy:dev-env
    restart: unless-stopped
    #healthcheck:
    #  test: "curl localhost:8080"
    environment:
      DB_MASTER: "teamworkpm_master"
    ports:
      - "80:80"
      - "8877:8877"
    build:
      context: ./haproxy/

  php1:
    container_name: "php1"
    restart: unless-stopped
    #healthcheck:
    #  test: "curl localhost:8080"
    environment:
      USERNAME: "bob"
    ports:
      - "8081:81"
    build:
      context: ./php1/

  php2:
    container_name: "php2"
    restart: unless-stopped
    #healthcheck:
    #  test: "curl localhost:8080"
    environment:
      USERNAME: "fred"
    ports:
      - "8082:82"
    build:
      context: ./php2/      

networks:
  default:
    external:
      name: haproxy